### ISSUE TITLE
Helm chart is broken

### ISSUE THREAD

**Issue by pzduniak** [mailgun/gubernator#130]
https://github.com/mailgun/gubernator/blob/master/deploy/helm/templates/_helpers.tpl#L101-L102

Env vars must be strings, this inserts a number. The value needs to be wrapped in `"`s.

I'm not fully convinced this has ever worked :) I'd fix this, but legally it would get complicated.

**Comment by pzduniak** [comment]
Another one!

```yaml
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gubernator.autoscaling.cpuAverageUsage }}
```

meanwhile in `values.yaml`:
```yaml
gubernator:

  fullnameOverride: {}
  nameOverride: {}
  priorityClassName: {}

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    cpuAverageUtilization: 50
```
note `cpuAverageUsage` vs `cpuAverageUtilization`
