### ISSUE TITLE
K8S Yaml does not properly grant permissions for the kubernetes API

### ISSUE THREAD

**Issue by andysnowden** [mailgun/gubernator#66]
Looks like gubernator is trying to use the "default" SA generated for whatever namespace it's deployed to.

`E0827 18:25:17.473059       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:guber:default" cannot list resource "endpoints" in API group "" in the namespace "guber"`

The K8S yaml needs to be updated to generate a ServiceAccount with the proper role bindings

**Comment by steers** [comment]
Something like below seems sufficient to get a gubernator cluster up and running, at least for testing purposes (which is what this manifest is ultimately geared towards).
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gubernator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-endpoints
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-endpoints
subjects:
- kind: ServiceAccount
  name: gubernator
```

Then, just patch the service account name into the deployment definition:
```yaml
spec:
  template:
    spec:
      serviceAccountName: gubernator
```
